---
title: "Cheyenne 101"
author: "Chuliang Xiao"
date: "4/17/2018"
output: 
  ioslides_presentation:
    widescreen: true
    incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Tentative Schedule
* Cheyenne101
* WRF and WRF-Hydro on Cheyenne
* Step-by-step on WRF
* WRF-Hydro & NWM
  + Introduction
  + Hydrofabric
  + Pre-processing
  + WRF-HydroCase
  + Post-processing
* Discussion.

## Traning
| |
|-----+---------------|
| Time | Tuesday 1-2 pm|
|Location| Ontario or Erie|
|Format| Hands-on|
|Discussion|Final 10 minutes|

# Cheyenne 101

## Hardware
| |
|-----+---------------|
| 145,152 processor cores |	2.3-GHz Intel Xeon E5-2697V4 (Broadwell) processors 16 flops per clock | 
| 4,032 computation nodes	| Dual-socket nodes, 18 cores per socket |
| 6 login nodes	| Dual-socket nodes, 18 cores per socket, 256 GB memory/node |
| 313 TB total system memory	| 64 GB/node on 3,168 nodes, DDR4-2400, 128 GB/node on 864 nodes, DDR4-2400 |
| Mellanox EDR InfiniBand, high-speed interconnect	|Partial 9D Enhanced Hypercube single-plane interconnect topology, Bandwidth: 25 GBps bidirectional per link, Latency: MPI ping-pong < 1 µs; hardware link 130 ns |
| 3 times Yellowstone computational capacity |	Comparison based on the relative performance of | the CISL High Performance Computing Benchmarks run on each system. |
| 3.5 times Yellowstone peak performance |	5.34 peak petaflops (vs. 1.504) |

